version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - dbdata:/var/lib/postgresql/data
  toxiproxy:
    image: shopify/toxiproxy 
    container_name: toxiproxy
    expose:
      - "8474"
    ports:
      - "22001:22001"
      - "8474:8474"
    depends_on:
      - db
  web:
    build: .
    container_name: web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Rails-Docker
    ports:
      - "3000:3000"
    depends_on:
      - toxiproxy    
        
volumes:
  dbdata:    